# Generated by Django 5.1.2 on 2024-10-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('room', models.CharField(max_length=240, verbose_name='Room')),
                ('shelf', models.CharField(max_length=240, verbose_name='Shelf')),
                ('subShelf', models.CharField(max_length=240, verbose_name='Sub-Shelf')),
                ('amount', models.IntegerField(max_length=240, verbose_name='Amount')),
            ],
        ),
    ]
