# Generated by Django 5.1.2 on 2024-10-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.IntegerField(verbose_name='Amount'),
        ),
    ]
