# Generated by Django 5.1.2 on 2024-10-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_item_room_remove_item_subshelf_item_aliases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='aliasestwo',
            field=models.CharField(default='unknown', max_length=240, verbose_name='Aliases'),
        ),
    ]
